# Generated by Django 3.1.3 on 2020-12-02 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='andriod_app_permisiion',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 23, 43, 43, 492486)),
        ),
        migrations.AddField(
            model_name='company_details',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='max_accesable_uuid_no',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='company_details',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company_details',
            name='primary_uuid',
            field=models.TextField(default=False, max_length=360),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='description',
            field=models.TextField(blank=True, max_length=360),
        ),
    ]
