# Generated by Django 3.1.3 on 2020-12-02 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20201202_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_details',
            old_name='email',
            new_name='company_email',
        ),
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 23, 44, 25, 759011)),
        ),
    ]
