# Generated by Django 3.1.3 on 2020-12-02 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20201202_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 23, 45, 23, 895724)),
        ),
    ]
