# Generated by Django 3.1.3 on 2020-12-02 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_auto_20201202_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='company_email',
        ),
        migrations.AddField(
            model_name='company_details',
            name='company_user_email',
            field=models.EmailField(default=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 23, 49, 20, 179585)),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='max_accesable_uuid_no',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
