# Generated by Django 3.1.3 on 2020-12-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_auto_20201202_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_user_email',
            field=models.EmailField(default=True, max_length=100),
        ),
    ]
