# Generated by Django 3.1.3 on 2020-12-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_auto_20201202_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='company',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
