# Generated by Django 3.1.3 on 2020-12-02 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_auto_20201202_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 23, 59, 24, 192512)),
        ),
    ]
