# Generated by Django 3.1.3 on 2020-12-02 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_company_details_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='company',
            field=models.CharField(default=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_user_email',
            field=models.CharField(default=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 0, 11, 11, 736950)),
        ),
    ]
