# Generated by Django 3.1.3 on 2020-12-03 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_auto_20201203_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 12, 27, 48, 451384)),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='company_details',
            unique_together={('company', 'company_user_email')},
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=1000)),
                ('primary_uuid', models.TextField(max_length=360)),
                ('max_accesable_uuid_no', models.CharField(default='1', max_length=200)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_branch_id', to='structure.company_details')),
            ],
        ),
    ]
