# Generated by Django 3.1.3 on 2020-12-05 06:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0015_auto_20201203_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch_deparments', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_deparments', to='structure.branches')),
            ],
        ),
        migrations.RemoveField(
            model_name='branche_uuids',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='company_uuids',
            name='company_id',
        ),
        migrations.AddField(
            model_name='branche_uuids',
            name='branch_uuid',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_uuid', to='structure.branches'),
        ),
        migrations.AddField(
            model_name='company_uuids',
            name='company_uuid',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_uuid', to='structure.company_details'),
        ),
        migrations.AlterField(
            model_name='branche_uuids',
            name='uuid',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 11, 49, 12, 78332)),
        ),
        migrations.AlterField(
            model_name='company_uuids',
            name='uuid',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department_wise_designation', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_wise_designation', to='structure.departments')),
            ],
        ),
    ]
