# Generated by Django 3.1.3 on 2020-12-05 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0017_auto_20201205_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 13, 31, 49, 230783)),
        ),
    ]
