# Generated by Django 3.1.3 on 2020-12-05 14:27

import datetime
from django.db import migrations, models
import structure.models
from  django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0018_auto_20201205_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='logo',
            field=models.ImageField(default='default_company_logo.jpg', upload_to=settings.MEDIA_ROOT),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 57, 20, 392115)),
        ),
    ]
