# Generated by Django 3.1.3 on 2020-12-06 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0020_auto_20201205_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 18, 20, 44, 843161)),
        ),
    ]
