# Generated by Django 3.1.3 on 2020-12-09 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0024_auto_20201209_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 22, 32, 28, 21297)),
        ),
    ]
