# Generated by Django 3.1.3 on 2020-12-09 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0026_auto_20201209_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 23, 21, 10, 915008)),
        ),
        migrations.CreateModel(
            name='Employeess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_branch_manager', models.BooleanField(default=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('SUSPENDED', 'suspend'), ('TRANSFERED', 'transfered')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_photo', models.ImageField(default='defalut_employee.jpg', upload_to='employee_photo')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_id', to='structure.branches')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='structure.company_details')),
                ('deparment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deparment_id', to='structure.departments')),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_id', to='structure.designations')),
            ],
            options={
                'unique_together': {('username', 'email')},
            },
        ),
    ]
