# Generated by Django 3.1.3 on 2020-12-09 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0027_auto_20201209_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeess',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeess',
            name='is_branch_manager',
        ),
        migrations.RemoveField(
            model_name='employeess',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='employeess',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 23, 35, 53, 861840)),
        ),
    ]
