# Generated by Django 3.1.3 on 2020-12-10 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0029_auto_20201209_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 10, 51, 50, 567945)),
        ),
        migrations.AlterField(
            model_name='employeess',
            name='profile_photo',
            field=models.ImageField(default='defalut_employee.png', upload_to='employee_photo'),
        ),
    ]
