# Generated by Django 3.1.3 on 2020-12-12 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0030_auto_20201210_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeess',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeess',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeess',
            name='sample_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 8, 48, 48, 184785)),
        ),
        migrations.AlterField(
            model_name='employeess',
            name='profile_photo',
            field=models.ImageField(default='defalut_employee.jpg', upload_to='employee_photo'),
        ),
        migrations.AlterField(
            model_name='employeess',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUSPENDED', 'suspend'), ('TRANSFERED', 'transfered'), ('LEFT', 'left')], default='ACTIVE', max_length=20),
        ),
    ]
