# Generated by Django 3.1.3 on 2020-12-12 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0031_auto_20201212_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeess',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employeess',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 22, 25, 59, 305942)),
        ),
    ]
