# Generated by Django 3.1.3 on 2020-12-13 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0036_auto_20201212_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 7, 53, 54, 260208)),
        ),
    ]
