# Generated by Django 3.1.3 on 2020-12-13 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0037_auto_20201213_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 21, 29, 742838)),
        ),
    ]
