# Generated by Django 3.1.3 on 2020-12-13 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0038_auto_20201213_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 21, 6, 54, 434457)),
        ),
    ]
