# Generated by Django 3.1.3 on 2020-12-14 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0039_auto_20201213_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 7, 55, 43, 598742)),
        ),
    ]
