# Generated by Django 3.1.3 on 2020-12-14 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0043_auto_20201214_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 10, 18, 24, 583355)),
        ),
    ]
