# Generated by Django 3.1.3 on 2020-12-15 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0045_auto_20201214_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 9, 44, 22, 714907)),
        ),
    ]
