# Generated by Django 3.0.5 on 2021-01-17 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0052_auto_20201219_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 14, 31, 28, 194294)),
        ),
    ]
