# Generated by Django 3.0.5 on 2021-01-17 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0053_auto_20210117_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 14, 32, 26, 286169)),
        ),
    ]
