# Generated by Django 3.0.5 on 2021-02-01 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0054_auto_20210117_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 19, 12, 42, 346564)),
        ),
    ]
