# Generated by Django 3.1.3 on 2020-12-13 15:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import workflow.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0039_auto_20201213_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('dead_line', models.DateTimeField(null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED')], default='PROCESSING', max_length=100)),
                ('branch_wise_workflow', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_wise_workflow', to='structure.branches')),
            ],
        ),
        migrations.CreateModel(
            name='Work_flow_employee_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('assignment', models.TextField(max_length=1000)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED')], default='PROCESSING', max_length=100)),
                ('emp_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_id', to='structure.employeess')),
                ('workflow_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_id', to='workflow.work_flow')),
            ],
        ),
        migrations.CreateModel(
            name='Uplodaed_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=workflow.models.content_file_name)),
                ('emp_id_uplodaed_file', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_id_uplodaed_file', to='structure.employeess')),
                ('workflow_id_uplodaed_file', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_id_uplodaed_file', to='workflow.work_flow')),
            ],
        ),
    ]
