# Generated by Django 3.1.3 on 2020-12-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uplodaed_file',
            name='remarks',
            field=models.CharField(default='', max_length=100),
        ),
    ]
