# Generated by Django 3.1.3 on 2020-12-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0041_auto_20201214_0921'),
        ('workflow', '0002_uplodaed_file_remarks'),
    ]


