# Generated by Django 3.1.3 on 2020-12-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20201214_0921'),
    ]
#
#     operations = [
#         migrations.AlterUniqueTogether(
#             name='work_flow_employee_detail',
#             unique_together=set(),
#         ),
#     ]
