# Generated by Django 3.1.3 on 2020-12-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20201214_1014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='work_flow_employee_detail',
            unique_together=set(),
        ),
    ]
