# Generated by Django 3.1.3 on 2020-12-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0045_auto_20201214_1948'),
        ('workflow', '0005_auto_20201214_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_flow',
            name='branch_wise_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_wise_workflow', to='structure.branches'),
        ),
        migrations.AlterField(
            model_name='work_flow',
            name='dead_line',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='work_flow_employee_detail',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_id', to='structure.employeess'),
        ),
        migrations.AlterField(
            model_name='work_flow_employee_detail',
            name='workflow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_id', to='workflow.work_flow'),
        ),
    ]
