# Generated by Django 3.1.3 on 2020-12-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0033_auto_20201212_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('intime', models.DateField(auto_now=True)),
                ('outtime', models.TimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id_wise_attendence', to='structure.employeess')),
            ],
            options={
                'unique_together': {('employee_id', 'date')},
            },
        ),
    ]
