# Generated by Django 3.1.3 on 2020-12-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='intime',
            field=models.TimeField(auto_now=True),
        ),
    ]
