# Generated by Django 3.1.3 on 2020-12-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_auto_20201212_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='in_time_recorded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendence',
            name='out_time_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='outtime',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
