# Generated by Django 3.1.3 on 2020-12-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
