# Generated by Django 3.0.5 on 2021-01-17 09:02

import apprizal.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0054_auto_20210117_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprizals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(null=True)),
                ('intime', models.TimeField(blank=True, null=True)),
                ('outtime', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=225)),
                ('aim', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=apprizal.models.content_file_name)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprizal_emp_id', to='structure.Employeess')),
            ],
        ),
    ]
